# Generated by Django 3.1.5 on 2021-02-06 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form_app3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='text',
            new_name='task_title',
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
