# Generated by Django 3.1.6 on 2021-02-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app4', '0002_auto_20210207_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_text',
            field=models.TextField(null=True),
        ),
    ]
